stages:
- name: build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-7
      shellScript: mvn clean package
- name: package
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: juixtu/2048:aws
      pushRemote: true
      registry: 10.199.11.141:10080
    env:
      PLUGIN_DEBUG: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./Deployment.yaml
    when:
      branch:
        include:
        - deploy
timeout: 60
branch:
  include:
  - master
notification: {}
